---
permalink: online-help/concept-what-active-iq-platform-events-are.html 
sidebar: sidebar 
keywords: Active IQ 
summary: Unified Manager kann Ereignisse anzeigen, die von der Active IQ Plattform erkannt wurden. Diese Ereignisse werden durch Regelwerke gegen AutoSupport Meldungen erstellt, die von allen Storage-Systemen, die von Unified Manager überwacht werden, generiert werden. 
---
= Was sind die Active IQ Plattform-Ereignisse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager kann Ereignisse anzeigen, die von der Active IQ Plattform erkannt wurden. Diese Ereignisse werden durch Regelwerke gegen AutoSupport Meldungen erstellt, die von allen Storage-Systemen, die von Unified Manager überwacht werden, generiert werden.

Unified Manager prüft automatisch auf eine neue Regeldatei und lädt nur eine neue Datei herunter, wenn neuere Regeln vorliegen. Bei Sites ohne externen Netzwerkzugriff müssen Sie die Regeln manuell von *Speicherverwaltung* > *Event-Setup* > *Upload-Regeln* hochladen.

Diese Active IQ Ereignisse überschneiden sich nicht mit bestehenden Unified Manager Ereignissen, und sie ermitteln Vorfälle oder Risiken bei Systemkonfiguration, Verkabelung, Best Practices und Verfügbarkeitsproblemen.

NetApp Active IQ ist ein cloudbasierter Service, der prädiktive Analysen und proaktiven Support zur Optimierung des Speichersystembetriebs in der NetApp Hybrid Cloud bietet. Siehe  https://docs.netapp.com/us-en/active-iq/index.html["NetApp Active IQ"^] für weitere Informationen.
