---
permalink: online-help/task-creating-the-volume-where-backups-are-stored.html 
sidebar: sidebar 
keywords:  
summary: Sie können das Volume erstellen, auf dem Snapshot Backups von ONTAP System Manager oder über die ONTAP CLI auf einem Ihrer ONTAP Cluster gespeichert werden. 
---
= Erstellung des Volumes, auf dem Backups gespeichert werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Volume erstellen, auf dem Snapshot Backups von ONTAP System Manager oder über die ONTAP CLI auf einem Ihrer ONTAP Cluster gespeichert werden.



== Bevor Sie beginnen

Der Cluster, die Storage-VM und das Volume müssen folgende Anforderungen erfüllen:

* Cluster-Anforderungen:
+
** ONTAP 9.3 oder höher muss installiert sein
** Sie sollten sich in geographischer Nähe zum Unified Manager-Server befinden
** Die Software kann zwar von Unified Manager überwacht werden, ist aber nicht erforderlich


* Storage-VM-Anforderungen:
+
** CIFS/SMB- oder NFS-Services müssen aktiviert sein
** Der Namensschalter und die Namenszuweisung müssen auf „`files`“ gesetzt werden.
** NFSv4 muss auf dem NFS-Server und der NFSv4-iddomain aktiviert sein, die auf dem Client und der Storage-VM angegeben ist
** Lokale Benutzer wurden erstellt, um den Client-seitigen Benutzern zu entsprechen
** Stellen Sie sicher, dass alle Lese-/Schreibzugriff ausgewählt ist
** Stellen Sie sicher, dass Superuser Access in der Exportrichtlinie auf „`any`“ eingestellt ist


* Volume-Anforderungen:
+
** Das Volume sollte mindestens die doppelte Größe des Unified Manager/opt/netapp/Datenververzeichnisses haben
+
Verwenden Sie den Befehl `du -sh /opt/netapp/data/` Um die aktuelle Größe zu überprüfen.

** Der Sicherheitsstil muss auf UNIX festgelegt sein
** Die lokale Snapshot-Richtlinie muss deaktiviert werden
** Die automatische Volume-Größe sollte aktiviert sein
** Das Performance-Service-Level sollte auf eine Richtlinie mit hohen IOPS-Werten und niedriger Latenz, wie z. B. „`Extreme`“, festgelegt werden.






== Über diese Aufgabe

Detaillierte Schritte zur Erstellung des NFS-Volume finden Sie unter https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_NFSv4_in_Cluster-Mode["So konfigurieren Sie NFSv4 in ONTAP 9"] Und das http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-nfsv3-cg/home.html["ONTAP 9 NFS Configuration Express Guide"].
