---
permalink: data-protection/reference-protection-storage-virtual-machine-associations-page.html 
sidebar: sidebar 
keywords:  
summary: Auf der Seite Storage VM Associations können Sie vorhandene SVM-Verknüpfungen zwischen Quell- und Ziel-SVMs anzeigen und neue SVM-Verknüpfungen erstellen, die von Partnerapplikationen genutzt werden können, um SnapMirror und SnapVault Beziehungen zu erstellen. 
---
= Seite „Storage VM Associations“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite Storage VM Associations können Sie vorhandene SVM-Verknüpfungen zwischen Quell- und Ziel-SVMs anzeigen und neue SVM-Verknüpfungen erstellen, die von Partnerapplikationen genutzt werden können, um SnapMirror und SnapVault Beziehungen zu erstellen.



== Befehlsschaltflächen

Mit den Schaltflächen können Sie die folgenden Aufgaben ausführen:

* *Erstellen*
+
Öffnet den Assistenten zum Erstellen von Storage Virtual Machine-Zuordnungen.

* *Löschen*
+
Hiermit können Sie die ausgewählten SVM-Zuordnungen löschen.





== Liste der SVM-Zuordnungen

Die Liste Storage Virtual Machine Associations wird in einer Tabelle die erstellten Quell- und Ziel-SVM-Zuordnungen sowie die Art der für jede Zuordnung zugelassenen Sicherungsbeziehung angezeigt.

* * Source Storage Virtual Machine*
+
Zeigt den Namen der Quell-SVM an.

* * Quellcluster*
+
Zeigt den Namen des Quell-Clusters an.

* *Zielspeicher Virtual Machine*
+
Zeigt den Namen der Ziel-SVM an.

* *Zielcluster*
+
Zeigt den Namen des Ziel-Clusters an.

* *Typ*
+
Zeigt die Art der Schutzbeziehung an. Beziehungstypen sind entweder SnapMirror oder SnapVault.


